language: python
python:
- '3.7'
install:
- pip install pipenv==2022.1.8
- pipenv install setuptools==60.5.0
- pipenv install --dev --skip-lock
script:
- echo "skipping tests"

jobs:
  include:
  - python: '3.7'
    dist: xenial
    sudo: true
  - stage: deploy
    if: tag IS present
    script: skip
    deploy:
      provider: pypi
      user: __token__
      password:
        secure: pypi-AgEIcHlwaS5vcmcCJDc3ZGU0ZTRjLTYwNjgtNDNiZS05NGIzLWQ1NGJkZDMzMTU2OQACKlszLCIwNTliNzQ3ZC1mMTE3LTQzN2QtOWFjZS0yNGU4ZmM3M2ZlMGUiXQAABiDlMWmo7h3bUI2q5j0qhYRMQdpgF8bqNnAvwhJ6ZcIRwQ
      on:
        tags: true
